name: Run Scraper

on:
  workflow_dispatch: # manually trigger it
  schedule:
    - cron: '0 3 * * *' # runs every day at 3 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧠 Run scraper
        run: node scripts/scrape-volunteermatch.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
